weights: ./models/st_gcn.ntu-xsub.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ../dataset/2023-3-29_北体合作_示范动作/st-gcn/val_data.npy
  label_path: ../dataset/2023-3-29_北体合作_示范动作/st-gcn/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'coco'
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 64

