work_dir: ./work_dir/recognition/pingpond/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: D:/Project/2023-GCN-action-recognize-tutorial/2023-GCN-action-recognize-tutorial/dataset/2023-3-29_北体合作_示范动作/train_data.npy
  label_path: D:/Project/2023-GCN-action-recognize-tutorial/2023-GCN-action-recognize-tutorial/dataset/2023-3-29_北体合作_示范动作/train_label.pkl
test_feeder_args:
  data_path: D:/Project/2023-GCN-action-recognize-tutorial/2023-GCN-action-recognize-tutorial/dataset/2023-3-29_北体合作_示范动作/val_data.npy
  label_path: D:/Project/2023-GCN-action-recognize-tutorial/2023-GCN-action-recognize-tutorial/dataset/2023-3-29_北体合作_示范动作/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'coco'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [ 10, 50 ]

# training
device: [ 0,1,2,3 ]
batch_size: 64
test_batch_size: 64
num_epoch: 80



